- name: Restart ssh
  ansible.builtin.systemd:
    name: "{{ 'sshd' if ansible_distribution in ['OracleLinux', 'RedHat', 'CentOS', 'Rocky', 'AlmaLinux'] else 'ssh' }}"
    state: restarted
  notify:
    - Reset SSH connection

- name: Reset SSH connection
  ansible.builtin.meta: reset_connection
